/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface P5Select {
        "placeholder": string;
        "value"?: any | null;
    }
    interface P5SelectOption {
        "value": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLP5SelectElement extends Components.P5Select, HTMLStencilElement {
    }
    var HTMLP5SelectElement: {
        prototype: HTMLP5SelectElement;
        new (): HTMLP5SelectElement;
    };
    interface HTMLP5SelectOptionElement extends Components.P5SelectOption, HTMLStencilElement {
    }
    var HTMLP5SelectOptionElement: {
        prototype: HTMLP5SelectOptionElement;
        new (): HTMLP5SelectOptionElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "p5-select": HTMLP5SelectElement;
        "p5-select-option": HTMLP5SelectOptionElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface P5Select {
        "placeholder"?: string;
        "value"?: any | null;
    }
    interface P5SelectOption {
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "p5-select": P5Select;
        "p5-select-option": P5SelectOption;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "p5-select": LocalJSX.P5Select & JSXBase.HTMLAttributes<HTMLP5SelectElement>;
            "p5-select-option": LocalJSX.P5SelectOption & JSXBase.HTMLAttributes<HTMLP5SelectOptionElement>;
        }
    }
}
